development:
  AWS_ACCESS_KEY_ID: 'AKIAIXAXFVIGLUKMFQ2Q'
  AWS_SECRET_ACCESS_KEY: '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'

test:
  AWS_ACCESS_KEY_ID: 'AKIAIXAXFVIGLUKMFQ2Q'
  AWS_SECRET_ACCESS_KEY: '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'

production:
  AWS_ACCESS_KEY_ID: 'AKIAIXAXFVIGLUKMFQ2Q'
  AWS_SECRET_ACCESS_KEY: '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'
